require('dotenv').config();

export const {
  POSTGRES_HOST,
  POSTGRES_PORT,
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DATABASE,
  PORT,
  NODE_ENV,
  ACCESS_KEY,
  REFRESH_TOKEN_KEY,
  ACCESS_TOKEN_MAX_AGE,
  REFRESH_TOKEN_MAX_AGE,
  SECRET_KEY,
  FLUTTERWAVE_ENC_KEY,
  FLUTTERWAVE_PUBLIC_KEY,
  FLUTTERWAVE_SECRET_KEY,
  FLUTTERWAVE_WEBHOOK_HASH,
} = process.env;
